import { Event } from './sanity'

export const sampleEvents: Event[] = [
  {
    _id: '1',
    title: 'Mindful Movement Session',
    date: '2025-07-05',
    time: '11AM - 2PM',
    type: 'MINDFUL MOVEMENT',
    location: 'Ramna Park',
    description: 'Join us for a transformative morning of mindful movement in the heart of Dhaka.',
    spots: '12 spots remaining',
    typeColor: 'bg-green-100 text-green-800',
    isActive: true,
    order: 1,
  },
  {
    _id: '2',
    title: 'Breathwork Circle',
    date: '2025-07-12',
    time: '9AM - 12PM',
    type: 'BREATHWORK CIRCLE',
    location: 'Dhanmondi Lake',
    description: 'Experience the power of conscious breathing by the serene waters of Dhanmondi Lake.',
    spots: '8 spots remaining',
    typeColor: 'bg-blue-100 text-blue-800',
    isActive: true,
    order: 2,
  },
  {
    _id: '3',
    title: 'Sunrise Yoga',
    date: '2025-07-19',
    time: '6:30 - 9AM',
    type: 'SUNRISE YOGA',
    location: 'Hatirjheel',
    description: 'Welcome the day with gentle yoga as the sun rises over Hatirjheel.',
    spots: '15 spots remaining',
    typeColor: 'bg-orange-100 text-orange-800',
    isActive: true,
    order: 3,
  },
  {
    _id: '4',
    title: 'Wellness Retreat',
    date: '2025-07-26',
    time: '10AM - 1PM',
    type: 'WELLNESS RETREAT',
    location: 'Baldha Garden',
    description: 'A half-day retreat combining yoga, meditation, and nature connection in Dhaka\'s botanical haven.',
    spots: '5 spots remaining',
    typeColor: 'bg-purple-100 text-purple-800',
    isActive: true,
    order: 4,
  },
  {
    _id: '5',
    title: 'Meditation Intensive',
    date: '2025-08-02',
    time: '9AM - 12PM',
    type: 'MEDITATION INTENSIVE',
    location: 'Suhrawardy Udyan',
    description: 'Deepen your meditation practice in one of Dhaka\'s most peaceful green spaces.',
    spots: '6 spots remaining',
    typeColor: 'bg-teal-100 text-teal-800',
    isActive: true,
    order: 5,
  },
  {
    _id: '6',
    title: 'Community Gathering',
    date: '2025-08-09',
    time: '10AM - 1PM',
    type: 'COMMUNITY GATHERING',
    location: 'Chandrima Udyan',
    description: 'Connect with fellow practitioners in a celebration of mindful community.',
    spots: '20 spots remaining',
    typeColor: 'bg-rose-100 text-rose-800',
    isActive: true,
    order: 6,
  },
] 